### ISSUE TITLE
No email address after successful authentication via GitHub

### ISSUE THREAD

**Issue by amelius123** [NerminKarapandzic/spring-boot-nextjs-starter-kit#2]
https://github.com/NerminKarapandzic/spring-boot-nextjs-starter-kit/blob/40a9a42b681f6b27a667532955c27f6154ebd803/backend/src/main/java/com/example/backend/auth/Oauth2LoginSuccessHandler.java#L44

I tried to authenticate using my own GitHub account. On that account, I don't have set a public email address. This results in the email being null. Does anyone have an idea of what could be used instead?

**Comment by NerminKarapandzic** [comment]
Well, if you want to keep the same logic where you want to allow users to be identified by their email addresses so they can have multiple connected acconts (google, facebook...) then there isn't really a workaround.
You can just change the logic in that handler so it only checks if there is a user by providerId and if not create one.
What this will in turn mean is if you have for example a google account and facebook account with the same email address, you could login to the app with google but then if you try to login with facebook you would login to a completely different account.

**Comment by amelius123** [comment]
Thank you for your answer. I retrieved the email address via a GET request to https://api.github.com/user/emails. By using the `OAuth2AuthenticationToken` and the `OAuth2AuthorizedClientService`, you can obtain an access token for the request. I also added `spring.security.oauth2.client.registration.github.scope=user:email` to application.properties.
